<<<<<<< HEAD
environment = "jollystation.dme"
=======
environment = "tgstation.dme"
>>>>>>> b4c08c4bd5e6dd7751287bbd05f6c0fc6e01ff1b

[langserver]
dreamchecker = true

[code_standards]
disallow_relative_type_definitions = true
disallow_relative_proc_definitions = true

[dmdoc]
use_typepath_names = true

[debugger]
engine = "auxtools"
